# Hide memory addresses to non-privileged users
kernel.kptr_restrict = 2
# Avoid malicious processes inspect memory from other process
kernel.yama.ptrace_scope = 1

# Prevent replacement files and symlinks attack
fs.protected_fifos = 2 
fs.protected_regular = 2