# Move this content or the file if does not exist on /etc/sysctl.d/

# Protect against IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Disable ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Disable sending ICMP redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Enable SYN flood protection
net.ipv4.tcp_syncookies = 1

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Ignore bogus ICMP error responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Optional: Disable IPv6 if not used
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1

# Prevents the system from acting as a router
net.ipv4.tcp_forward = 0

# Prevent time-wait assassination attacks
net.ipv4.tcp_rfc1337 = 1

# Reduces the risk of certain types of time-based attacks
net.ipv4.tcp_timestamps = 0

# Protects against smurf attacks
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disables all ICMP echo requests (ping), making the system less detectable to attackers via network scanning
net.ipv4.icmp_echo_ignore_all = 1

# Reduce the risk of exploitation through specific TCP vulnerabilities, at the cost of performance in some scenarios. 
net.ipv4.tcp_sack = 0
net.ipv4.tcp_dsack = 0
net.ipv4.tcp_fsack = 0

# Prevent the system from accepting potentially malicious routing information, thereby protecting against man-in-the-middle attacks
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
